// AgriSystem — Complete Crop & Seed Dataset
const crops = [
  {
    id: 1, name: "Wheat", image: "🌾", category: "cereal",
    season: ["rabi", "winter"],
    soil_types: ["loamy", "clay", "alluvial"],
    climate: ["cool", "temperate"],
    water_requirement: "medium",
    sowing_months: ["October", "November", "December"],
    harvest_months: ["March", "April"],
    duration_days: "120-150",
    description: "Wheat is a staple cereal crop grown in cool, dry climates. One of the most widely cultivated crops worldwide.",
    care_tips: ["Irrigate 4–6 times during growing period","Apply nitrogen fertilizer at sowing and top-dress after 3 weeks","Watch for rust disease — use resistant varieties","Ensure well-drained soil to avoid waterlogging"],
    seeds: { type: "Grain Seed", sowing_depth_cm: "5-7", seed_rate_kg_per_acre: "40-50", germination_days: "7-10", spacing_cm: "20-22 (row)" }
  },
  {
    id: 2, name: "Rice", image: "🍚", category: "cereal",
    season: ["kharif", "summer"],
    soil_types: ["clay", "alluvial", "loamy"],
    climate: ["hot", "humid", "tropical"],
    water_requirement: "high",
    sowing_months: ["June", "July"],
    harvest_months: ["October", "November"],
    duration_days: "120-160",
    description: "Rice is the most important food crop in Asia. Requires standing water during most of its growth period.",
    care_tips: ["Maintain 5–10 cm standing water in fields","Transplant seedlings 25–30 days after nursery sowing","Top dress urea at tillering stage","Drain field 2 weeks before harvest"],
    seeds: { type: "Paddy Seed", sowing_depth_cm: "2-3 (nursery)", seed_rate_kg_per_acre: "8-10", germination_days: "5-8", spacing_cm: "20×15 (transplanted)" }
  },
  {
    id: 3, name: "Maize", image: "🌽", category: "cereal",
    season: ["kharif", "summer"],
    soil_types: ["loamy", "sandy-loam", "alluvial"],
    climate: ["warm", "tropical", "subtropical"],
    water_requirement: "medium",
    sowing_months: ["June", "July", "February"],
    harvest_months: ["September", "October"],
    duration_days: "90-110",
    description: "Maize is a versatile crop used for food, fodder, and industrial products. Grows best in warm, well-drained soils.",
    care_tips: ["Sow seeds on ridges or raised beds","Irrigate at knee-high stage and silking stage","Apply balanced NPK fertilizer","Control stem borer with appropriate pesticide"],
    seeds: { type: "Hybrid / Open-Pollinated", sowing_depth_cm: "4-5", seed_rate_kg_per_acre: "8-10", germination_days: "6-10", spacing_cm: "60×25" }
  },
  {
    id: 4, name: "Cotton", image: "🪴", category: "cash_crop",
    season: ["kharif", "summer"],
    soil_types: ["black", "clay", "deep-loam"],
    climate: ["hot", "tropical", "subtropical"],
    water_requirement: "medium",
    sowing_months: ["April", "May", "June"],
    harvest_months: ["October", "November", "December"],
    duration_days: "150-180",
    description: "Cotton is a major cash crop grown for its fiber. Thrives in hot climates with deep, well-drained soils.",
    care_tips: ["Sow after last frost when soil is warm","Thin to 1 plant per hill after germination","Monitor for bollworm and whitefly","Reduce irrigation at boll maturity"],
    seeds: { type: "Hybrid / Bt Cotton", sowing_depth_cm: "3-5", seed_rate_kg_per_acre: "1-1.5 kg", germination_days: "7-10", spacing_cm: "90×60" }
  },
  {
    id: 5, name: "Tomato", image: "🍅", category: "vegetable",
    season: ["rabi", "kharif", "winter", "summer"],
    soil_types: ["loamy", "sandy-loam", "alluvial"],
    climate: ["warm", "temperate"],
    water_requirement: "medium",
    sowing_months: ["June", "July", "October", "November"],
    harvest_months: ["September", "October", "January", "February"],
    duration_days: "60-80",
    description: "Tomato is one of the most popular vegetable crops. Can be grown in multiple seasons, rich in vitamins.",
    care_tips: ["Start seeds in nursery trays 30 days before transplanting","Stake plants when 30 cm tall","Irrigate regularly — avoid waterlogging","Spray fungicide to prevent early blight"],
    seeds: { type: "Hybrid Vegetable Seed", sowing_depth_cm: "0.5-1", seed_rate_kg_per_acre: "0.1-0.15 kg", germination_days: "5-7", spacing_cm: "75×60" }
  },
  {
    id: 6, name: "Sugarcane", image: "🎋", category: "cash_crop",
    season: ["annual"],
    soil_types: ["loamy", "clay", "alluvial"],
    climate: ["tropical", "subtropical", "hot"],
    water_requirement: "high",
    sowing_months: ["February", "March", "October"],
    harvest_months: ["November", "December", "January"],
    duration_days: "300-360",
    description: "Sugarcane is the primary source of sugar and ethanol. Long-duration crop requiring high water input.",
    care_tips: ["Use healthy 2-3 budded setts for planting","Provide earthing up at 90 days","Irrigate every 10–15 days","Control top borer during early growth"],
    seeds: { type: "Stem Cuttings (Setts)", sowing_depth_cm: "10-15", seed_rate_kg_per_acre: "2500-3000 setts", germination_days: "15-21", spacing_cm: "90×30" }
  },
  {
    id: 7, name: "Potato", image: "🥔", category: "vegetable",
    season: ["rabi", "winter"],
    soil_types: ["sandy-loam", "loamy", "alluvial"],
    climate: ["cool", "temperate"],
    water_requirement: "medium",
    sowing_months: ["October", "November"],
    harvest_months: ["January", "February", "March"],
    duration_days: "80-110",
    description: "Potato is a major vegetable crop grown in cool weather. Grown from tubers and rich in carbohydrates.",
    care_tips: ["Use certified, disease-free seed tubers","Hill up soil around plants at 30 days","Irrigate every 7–10 days","Spray fungicide to prevent late blight"],
    seeds: { type: "Seed Tubers", sowing_depth_cm: "8-10", seed_rate_kg_per_acre: "500-600 kg", germination_days: "14-21", spacing_cm: "60×20" }
  },
  {
    id: 8, name: "Sunflower", image: "🌻", category: "oilseed",
    season: ["kharif", "rabi", "summer"],
    soil_types: ["loamy", "sandy-loam", "black"],
    climate: ["warm", "temperate", "cool"],
    water_requirement: "low",
    sowing_months: ["June", "July", "October", "January"],
    harvest_months: ["September", "October", "March"],
    duration_days: "90-100",
    description: "Sunflower is an important oilseed crop that can be grown in multiple seasons. Drought-tolerant and adaptable.",
    care_tips: ["Sow 2 seeds per hill, thin to 1 after germination","Apply boron micronutrient to improve seed setting","Irrigate at flowering and seed-filling stages","Protect from birds during seed filling"],
    seeds: { type: "Hybrid Oilseed", sowing_depth_cm: "3-5", seed_rate_kg_per_acre: "2-2.5 kg", germination_days: "6-8", spacing_cm: "60×30" }
  },
  {
    id: 9, name: "Chickpea", image: "🫘", category: "pulse",
    season: ["rabi", "winter"],
    soil_types: ["loamy", "sandy-loam", "black"],
    climate: ["cool", "dry", "temperate"],
    water_requirement: "low",
    sowing_months: ["October", "November"],
    harvest_months: ["February", "March"],
    duration_days: "100-120",
    description: "Chickpea is a drought-tolerant pulse crop that fixes nitrogen in the soil. Rich source of protein.",
    care_tips: ["Treat seeds with Rhizobium culture before sowing","Avoid excess irrigation — 1–2 irrigations sufficient","Monitor for pod borer at flowering","Harvest when leaves turn yellow and pods are dry"],
    seeds: { type: "Pulse Seed", sowing_depth_cm: "5-8", seed_rate_kg_per_acre: "30-35 kg", germination_days: "8-12", spacing_cm: "30×10" }
  },
  {
    id: 10, name: "Mango", image: "🥭", category: "fruit",
    season: ["perennial"],
    soil_types: ["loamy", "alluvial", "laterite"],
    climate: ["tropical", "subtropical", "hot"],
    water_requirement: "low",
    sowing_months: ["July", "August"],
    harvest_months: ["April", "May", "June"],
    duration_days: "1800+ (5 yrs first fruit)",
    description: "Mango is the king of fruits and a major horticultural crop. Grafted plants bear fruit in 3–4 years.",
    care_tips: ["Use grafted plants for early and reliable fruiting","Apply farmyard manure in July–August every year","Irrigate young trees weekly; mature trees before flowering","Prune dead wood after harvest"],
    seeds: { type: "Grafted Sapling", sowing_depth_cm: "10-15", seed_rate_kg_per_acre: "16-20 plants", germination_days: "14-21", spacing_cm: "1000×1000 (10m)" }
  },
  {
    id: 11, name: "Onion", image: "🧅", category: "vegetable",
    season: ["rabi", "kharif"],
    soil_types: ["loamy", "sandy-loam", "alluvial"],
    climate: ["cool", "temperate", "warm"],
    water_requirement: "medium",
    sowing_months: ["October", "November", "June"],
    harvest_months: ["February", "March", "September"],
    duration_days: "100-120",
    description: "Onion is one of the most important commercial vegetable crops used worldwide as a condiment and vegetable.",
    care_tips: ["Transplant 6-week-old nursery seedlings","Irrigate every 7-10 days; stop 10 days before harvest","Apply potassium for better bulb development","Control thrips with neem oil spray"],
    seeds: { type: "Bulb Seed / Sets", sowing_depth_cm: "1-2", seed_rate_kg_per_acre: "3-4 kg", germination_days: "8-12", spacing_cm: "15×10" }
  },
  {
    id: 12, name: "Groundnut", image: "🥜", category: "oilseed",
    season: ["kharif", "summer"],
    soil_types: ["sandy-loam", "loamy", "red"],
    climate: ["warm", "tropical", "subtropical"],
    water_requirement: "medium",
    sowing_months: ["June", "July", "January"],
    harvest_months: ["September", "October", "April"],
    duration_days: "100-130",
    description: "Groundnut is a major oilseed and food crop. It fixes atmospheric nitrogen and improves soil fertility.",
    care_tips: ["Shell seeds just before sowing for best germination","Earthing up is essential for pod development","Avoid waterlogging — causes collar rot","Apply gypsum at pegging stage for calcium"],
    seeds: { type: "Oilseed (Kernel)", sowing_depth_cm: "4-6", seed_rate_kg_per_acre: "50-60 kg", germination_days: "7-10", spacing_cm: "30×10" }
  },
  { id: 13, name: "Barley", image: "🥖", category: "cereal", season: ["rabi","winter"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "low", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Barley prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 14, name: "Sorghum", image: "🌿", category: "cereal", season: ["kharif","summer"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "low", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Sorghum prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 15, name: "Pearl Millet", image: "🌾", category: "cereal", season: ["kharif","summer"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "low", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Pearl Millet prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 16, name: "Oats", image: "🥣", category: "cereal", season: ["rabi","winter"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Oats prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 17, name: "Rye", image: "🌾", category: "cereal", season: ["rabi","winter"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "low", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Rye prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 18, name: "Quinoa", image: "🥗", category: "cereal", season: ["rabi","winter"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "low", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Quinoa prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 19, name: "Buckwheat", image: "🥞", category: "cereal", season: ["kharif"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Buckwheat prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 20, name: "Cabbage", image: "🥬", category: "vegetable", season: ["rabi","winter"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Cabbage prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 21, name: "Cauliflower", image: "🥦", category: "vegetable", season: ["rabi","winter"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Cauliflower prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 22, name: "Broccoli", image: "🌳", category: "vegetable", season: ["rabi","winter"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Broccoli prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 23, name: "Spinach", image: "🍃", category: "vegetable", season: ["rabi","winter"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "high", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Spinach prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 24, name: "Lettuce", image: "🥗", category: "vegetable", season: ["rabi","winter"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Lettuce prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 25, name: "Carrot", image: "🥕", category: "vegetable", season: ["rabi","winter"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Carrot prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 26, name: "Radish", image: "📍", category: "vegetable", season: ["rabi","winter"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Radish prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 27, name: "Beetroot", image: "🩸", category: "vegetable", season: ["rabi","winter"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Beetroot prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 28, name: "Garlic", image: "🧄", category: "vegetable", season: ["rabi","winter"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Garlic prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 29, name: "Ginger", image: "🫚", category: "vegetable", season: ["kharif"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Ginger prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 30, name: "Turmeric", image: "🪵", category: "vegetable", season: ["kharif"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Turmeric prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 31, name: "Capsicum", image: "🫑", category: "vegetable", season: ["kharif","rabi"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Capsicum prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 32, name: "Chili", image: "🌶️", category: "vegetable", season: ["kharif","rabi","summer"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Chili prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 33, name: "Brinjal", image: "🍆", category: "vegetable", season: ["kharif","rabi","summer"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Brinjal prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 34, name: "Okra", image: "🥒", category: "vegetable", season: ["kharif","summer"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Okra prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 35, name: "Pumpkin", image: "🎃", category: "vegetable", season: ["kharif","summer"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Pumpkin prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 36, name: "Cucumber", image: "🥒", category: "vegetable", season: ["kharif","summer"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "high", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Cucumber prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 37, name: "Bitter Gourd", image: "🐉", category: "vegetable", season: ["kharif","summer"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Bitter Gourd prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 38, name: "Bottle Gourd", image: "🍐", category: "vegetable", season: ["kharif","summer"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Bottle Gourd prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 39, name: "Green Beans", image: "🫘", category: "vegetable", season: ["kharif","rabi"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Green Beans prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 40, name: "Peas", image: "🟢", category: "vegetable", season: ["rabi","winter"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Peas prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 41, name: "Sweet Potato", image: "🍠", category: "vegetable", season: ["kharif","rabi"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Sweet Potato prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 42, name: "Cassava", image: "🪵", category: "vegetable", season: ["perennial","annual"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "low", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Cassava prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 43, name: "Yam", image: "🍠", category: "vegetable", season: ["kharif","annual"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Yam prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 44, name: "Banana", image: "🍌", category: "fruit", season: ["perennial"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "high", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Banana prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 45, name: "Orange", image: "🍊", category: "fruit", season: ["perennial"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Orange prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 46, name: "Grape", image: "🍇", category: "fruit", season: ["perennial"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Grape prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 47, name: "Papaya", image: "🥭", category: "fruit", season: ["perennial"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "high", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Papaya prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 48, name: "Guava", image: "🍏", category: "fruit", season: ["perennial"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Guava prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 49, name: "Pineapple", image: "🍍", category: "fruit", season: ["perennial"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Pineapple prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 50, name: "Watermelon", image: "🍉", category: "fruit", season: ["summer"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "high", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Watermelon prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 51, name: "Muskmelon", image: "🍈", category: "fruit", season: ["summer"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "high", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Muskmelon prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 52, name: "Pomegranate", image: "🔴", category: "fruit", season: ["perennial"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Pomegranate prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 53, name: "Lemon", image: "🍋", category: "fruit", season: ["perennial"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Lemon prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 54, name: "Coconut", image: "🥥", category: "fruit", season: ["perennial"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "high", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Coconut prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 55, name: "Jackfruit", image: "🟡", category: "fruit", season: ["perennial"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Jackfruit prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 56, name: "Jute", image: "🪢", category: "cash_crop", season: ["kharif"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "high", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Jute prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 57, name: "Tea", image: "🍃", category: "cash_crop", season: ["perennial"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "high", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Tea prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 58, name: "Coffee", image: "☕", category: "cash_crop", season: ["perennial"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Coffee prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 59, name: "Rubber", image: "🛞", category: "cash_crop", season: ["perennial"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "high", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Rubber prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 60, name: "Tobacco", image: "🚬", category: "cash_crop", season: ["rabi","kharif"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Tobacco prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 61, name: "Mustard", image: "🌼", category: "oilseed", season: ["rabi","winter"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "low", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Mustard prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } },
  { id: 62, name: "Soybean", image: "🫘", category: "oilseed", season: ["kharif"], soil_types: ["loamy","alluvial","sandy-loam"], climate: ["warm","temperate"], water_requirement: "medium", sowing_months: ["June","July"], harvest_months: ["October","November"], duration_days: "90-120", description: "A resilient crop widely cultivated for its uses. Soybean prefers a supportive climate.", care_tips: ["Ensure proper soil drainage","Monitor for pests during early growth phases","Apply balanced fertilizers"], seeds: { type: "Standard Seed", sowing_depth_cm: "2-5", seed_rate_kg_per_acre: "5-10", germination_days: "7-14", spacing_cm: "30x10" } }
];

const seasons = [
  { id: "kharif",   label: "Kharif",    months: "June – October",   emoji: "🌧️", description: "Monsoon / summer crops sown at onset of rains" },
  { id: "rabi",     label: "Rabi",      months: "Oct – March",      emoji: "❄️", description: "Winter crops sown after monsoon withdrawal" },
  { id: "summer",   label: "Summer",    months: "Feb – June",       emoji: "☀️", description: "Short-duration warm-season crops" },
  { id: "annual",   label: "Annual",    months: "Year-round",       emoji: "📅", description: "Long-duration crops grown for a full year" },
  { id: "perennial",label: "Perennial", months: "Multi-year",       emoji: "🌳", description: "Trees and long-term horticultural crops" }
];

const soilTypes = [
  { id: "alluvial",   label: "Alluvial Soil",  emoji: "🟤", description: "Fertile, found in river plains. Best for most crops." },
  { id: "black",      label: "Black Soil",     emoji: "⚫", description: "Rich in clay, retains moisture. Ideal for cotton." },
  { id: "loamy",      label: "Loamy Soil",     emoji: "🟫", description: "Balanced texture, best all-purpose agricultural soil." },
  { id: "sandy-loam", label: "Sandy Loam",     emoji: "🟡", description: "Well-draining, good for root vegetables and pulses." },
  { id: "clay",       label: "Clay Soil",      emoji: "🔵", description: "Heavy, water-retentive. Good for paddy and sugarcane." },
  { id: "laterite",   label: "Laterite Soil",  emoji: "🔴", description: "Iron-rich, acidic. Suited for mangoes and cashews." }
];

module.exports = { crops, seasons, soilTypes };
